### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by catvatar** [catvatar/Sin#1]
Literally anything, just make it beautiful.

**Comment by parzuko** [comment]
Can i make a python script to send emails ?

**Comment by catvatar** [comment]
Sure my boy

**Comment by canigethellomoto** [comment]
Can I add some cipher programs in Java like Vernam Cipher, Affine Cipher, Playfair Cipher?

**Comment by chiragjagad** [comment]
Hey, I would like to work on this!
Cheers!

**Comment by catvatar** [comment]
If you consider it beautiful, add it. Just don't add anything offensive

**Comment by chiragjagad** [comment]
> If you consider it beautiful, add it. Just don't add anything offensive

Planning to add an exercise tracker!
